version: "3.9"

services:
  api:
    build: .
    container_name: intranet_gestion_mail_api
    restart: unless-stopped
    expose:
      - "8001"
    env_file:
      - .env
    volumes:
      - /home/ec2-user/.aws:/root/.aws:ro
    networks:
      - intranet_gestion_auth_network

networks:
  intranet_gestion_auth_network:
    external: true